### ISSUE TITLE
cómo estás accediendo a los datos de json?

### ISSUE THREAD

**Issue by isclalo801** [EcommerceBBVA/BBVA-PHP#7]
cómo estás accediendo a los datos de json?

_Originally posted by @Grimmgalohm in https://github.com/EcommerceBBVA/BBVA-PHP/issues/4#issuecomment-675602358_

Implemente  esto, por que mire que si regresa los datos pero no puedo acceder a ellos 
```
$bbva = Bbva::getInstance($keyID, $idSDK);

        $chargeRequest = array(
            'affiliation_bbva' =>$BBVAaffiliation',
            'amount' => 100,
            'description' => 'Cargo inicial a mi merchant',
            'currency' => 'MXN',
            'order_id' => 'oid-' . $idCarrito,
            'redirect_url' => 'https://sand-portal.ecommercebbva.com',
            'customer' => array(
                'name' => 'Juan',
                'last_name' => 'Vazquez Juarez',
                'email' => 'juan.vazquez@empresa.com.mx',
                'phone_number' => '554-170-3567'
            )
        );

        $charge = $bbva->charges->create($chargeRequest);
        $array = (array)  $charge;
        foreach ($array as $key => $val) {
            $new_array[str_replace('*', '', $key)] = $val;
        }
        foreach ($new_array as $key => $val) {
            $new_array2[str_replace(' ', '', $key)] = $val;
        }
```

**Comment by Pabloaustria** [comment]
> cómo estás accediendo a los datos de json?
> 
> _Originally posted by @Grimmgalohm in [#4 (comment)](https://github.com/EcommerceBBVA/BBVA-PHP/issues/4#issuecomment-675602358)_
> 
> Implemente esto, por que mire que si regresa los datos pero no puedo acceder a ellos
> 
> ```
> $bbva = Bbva::getInstance($keyID, $idSDK);
> 
>         $chargeRequest = array(
>             'affiliation_bbva' =>$BBVAaffiliation',
>             'amount' => 100,
>             'description' => 'Cargo inicial a mi merchant',
>             'currency' => 'MXN',
>             'order_id' => 'oid-' . $idCarrito,
>             'redirect_url' => 'https://sand-portal.ecommercebbva.com',
>             'customer' => array(
>                 'name' => 'Juan',
>                 'last_name' => 'Vazquez Juarez',
>                 'email' => 'juan.vazquez@empresa.com.mx',
>                 'phone_number' => '554-170-3567'
>             )
>         );
> 
>         $charge = $bbva->charges->create($chargeRequest);
>         $array = (array)  $charge;
>         foreach ($array as $key => $val) {
>             $new_array[str_replace('*', '', $key)] = $val;
>         }
>         foreach ($new_array as $key => $val) {
>             $new_array2[str_replace(' ', '', $key)] = $val;
>         }
> ```


Alguien sabe como acceder a los datos?

**Comment by isclalo801** [comment]
> > ¿cómo estás accediendo a los datos de json?
> > _Publicado originalmente por @Grimmgalohm en el [# 4 (comentario)](https://github.com/EcommerceBBVA/BBVA-PHP/issues/4#issuecomment-675602358)_
> > Implemente esto, por que mire que si regresa los datos pero no puedo acceder a ellos
> > ```
> > $bbva = Bbva::getInstance($keyID, $idSDK);
> > 
> >         $chargeRequest = array(
> >             'affiliation_bbva' =>$BBVAaffiliation',
> >             'amount' => 100,
> >             'description' => 'Cargo inicial a mi merchant',
> >             'currency' => 'MXN',
> >             'order_id' => 'oid-' . $idCarrito,
> >             'redirect_url' => 'https://sand-portal.ecommercebbva.com',
> >             'customer' => array(
> >                 'name' => 'Juan',
> >                 'last_name' => 'Vazquez Juarez',
> >                 'email' => 'juan.vazquez@empresa.com.mx',
> >                 'phone_number' => '554-170-3567'
> >             )
> >         );
> > 
> >         $charge = $bbva->charges->create($chargeRequest);
> >         $array = (array)  $charge;
> >         foreach ($array as $key => $val) {
> >             $new_array[str_replace('*', '', $key)] = $val;
> >         }
> >         foreach ($new_array as $key => $val) {
> >             $new_array2[str_replace(' ', '', $key)] = $val;
> >         }
> > ```
> 
> Alguien sabe como acceder a los datos?

Si, logre acceder a los datos con este código
`require_once 'BBVA/Bbva.php';
        $bbva = Bbva::getInstance($id, $apiKey);

        $charge = $bbva->charges->get($idOperacion);        
        $serializableData=($charge->serializableData);
        return json_encode(array(
            'ok' => 1,
            'ID' => $charge->id,
            'serializableData' => $serializableData['status'],
            'url' => $serializableData['payment_method']->url,
            'creation_date' => $serializableData['creation_date'],
            'operation_date' => $serializableData['operation_date'],
        ));`
